# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BLOG | GKCY
email: frendchen1997@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Beautiful at the distance.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _StarLuck
github_username:  GKCY

# Build settings
markdown: kramdown

# redcarpet: 
#     extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]

